const fakedata = [
    {
        "id": 1,
        "name": "Apple per 1kg",
        "category": "food",
        "image": "https://freepngimg.com/thumb/apple/9-apple-png-image-thumb.png",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",

    },
    {
        "id": 2,
        "category": "food",
        "name": "Orange is very tasty",
        "image": "https://preview.colorlib.com/theme/ogani/img/categories/cat-1.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },

    {
        "id": 3,
        "category": "food",
        "name": "Banena",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-2.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    {
        "id": 4,
        "name": "Mango",
        "category": "food",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    {
        "id": 5,
        "name": "Mango",
        "category": "food",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    {
        "id": 6,
        "name": "Mango",
        "category": "food",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    {
        "id": 7,
        "name": "Mango",
        "category": "food",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    {
        "id": 8,
        "name": "Mango",
        "category": "food",
        "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
        "price" : 150,
        "stock": 10,
        "quantity": 1,
        "available": true,
        "rating": 5,
        "unit": "kg",
        "description": "slkdjastyegfaksjdfhbaywtefas dsduiyfgsudyftaks sjdhfgiasieuruytbfcsajhgf",
    },
    // {
    //     "id": 5,
    //     "name": "Angor fall",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-5.jpg",
    //     "price" : 160,
    // },
    // {
    //     "id": 6,
    //     "name": "Bargar",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-6.jpg",
    //     "price" : 300,
    // },
    // {
    //     "id": 7,
    //     "name": "Tometo",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/latest-product/lp-2.jpg",
    //     "price" : 50,
    // },
    // {
    //     "id": 8,
    //     "name": "Guva",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-3.jpg",
    //     "price" : 150,
    // },
    // {
    //     "id": 9,
    //     "name": "Watermenol",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-4.jpg",
    //     "price" : 450,
    // },
    // {
    //     "id": 10,
    //     "name": "Meat",
    //     "img": "https://preview.colorlib.com/theme/ogani/img/categories/cat-5.jpg",
    //     "price" : 1000,
    // }

]

export default fakedata;