export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_SPECIAL_PRODUCT = 'GET_SPECIAL_PRODUCT'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CART_ITEM_INCREMENT = 'CART_ITEM_INCREMENT'
export const CART_ITEM_DECREMENT = 'CART_ITEM_DECREMENT'


export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL'
export const REGISTRATION_VERIFY = 'REGISTRATION_VERIFY'
export const LOAD_USER = 'LOAD_USER'
export const LOGOUT = 'LOGOUT'

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const GET_WISHLIST = 'GET_WISHLIST';
export const CHANGE_ADD_TO_CART_OPTION = 'CHANGE_ADD_TO_CART_OPTION';
export const CHANGE_ADD_TO_WISHLIST_OPTION = 'CHANGE_ADD_TO_WISHLIST_OPTION';


export const CREATE_ORDER_CASH_ON_DELIVERY = 'CREATE_ORDER_CASH_ON_DELIVERY';
export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDERER = 'GET_ORDERER';
export const CANCEL_ORDERER = 'CANCEL_ORDERER';

export const AMOUNT_COUNT = 'AMOUNT_COUNT';

export const CHANGE_SHOP_ADD_TO_CART_OPTION = 'CHANGE_SHOP_ADD_TO_CART_OPTION';
export const CHANGE_SHOP_ADD_TO_WISHLIST_OPTION  = 'CHANGE_SHOP_ADD_TO_WISHLIST_OPTION';

export const CHANGE_SPACIALPRODUCTS_ADD_TO_CART  = 'CHANGE_SPACIALPRODUCTS_ADD_TO_CART';




