export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CART_ITEM_INCREMENT = 'CART_ITEM_INCREMENT'
export const CART_ITEM_DECREMENT = 'CART_ITEM_DECREMENT'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL'
export const REGISTRATION_VERIFY = 'REGISTRATION_VERIFY'
export const LOAD_USER = 'LOAD_USER'
export const LOGOUT = 'LOGOUT'

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const GET_WISHLIST = 'GET_WISHLIST';
