const detailsProductFakeData = [
  {
      "_id": 1,
      "name": "Apple per 1kg",
      "category": "food",
      "image": "https://freepngimg.com/thumb/apple/9-apple-png-image-thumb.png",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",

  },
  {
      "_id": 2,
      "name": "Orange is very tasty",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/categories/cat-1.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },

  {
      "_id": 3,
      "name": "Banena",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-2.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },
  {
      "_id": 4,
      "name": "Mango",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },
  {
      "_d": 5,
      "name": "Mango",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },
  {
      "_id": 6,
      "name": "Mango",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },
  {
      "_id": 7,
      "name": "Mango",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
  },
  {
      "_id": 8,
      "name": "Mango",
      "category": "food",
      "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
      "price" : 150,
      "stock": 10,
      "quantity": 1,
      "available": true,
      "rating": 5,
      "unit": "kg",
      "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48 ",
  },
  // {
  //     "id": 5,
  //     "name": "Angor fall",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-5.jpg",
  //     "price" : 160,
  // },
  // {
  //     "id": 6,
  //     "name": "Bargar",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-6.jpg",
  //     "price" : 300,
  // },
  // {
  //     "id": 7,
  //     "name": "Tometo",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/latest-product/lp-2.jpg",
  //     "price" : 50,
  // },
  // {
  //     "id": 8,
  //     "name": "Guva",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-3.jpg",
  //     "price" : 150,
  // },
  // {
  //     "id": 9,
  //     "name": "Watermenol",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/featured/feature-4.jpg",
  //     "price" : 450,
  // },
  // {
  //     "id": 10,
  //     "name": "Meat",
  //     "img": "https://preview.colorlib.com/theme/ogani/img/categories/cat-5.jpg",
  //     "price" : 1000,
  // }

]

export default detailsProductFakeData;