const fakewishlist = [
//   {
//     "_id": 3,
//     "name": "Banena",
//     "category": "Vegetables",
//     "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-2.jpg",
//     "price" : 150,
//     "specialPrice":140,
//     "stock": 10,
//     "quantity": 1,
//     "available": true,
//     "rating": 5,
//     "unit": "kg",
//     "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
// },
// {
//     "_id": 4,
//     "name": "Mango",
//     "category": "Fruit & Nut Gifts",
//     "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
//     "price" : 150,
//     "specialPrice":140,
//     "stock": 10,
//     "quantity": 1,
//     "available": true,
//     "rating": 5,
//     "unit": "kg",
//     "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
// },
// {
//     "_d": 5,
//     "name": "Mango",
//     "category": "Fresh Berries",
//     "image": "https://preview.colorlib.com/theme/ogani/img/featured/feature-7.jpg",
//     "price" : 150,
//     "specialPrice":140,
//     "stock": 10,
//     "quantity": 1,
//     "available": true,
//     "rating": 5,
//     "unit": "kg",
//     "description": "Brand : SSB Model No : SB-B42 Made In Bangladesh Marketed By Shaver Shop Bangladesh Order by phone get product :09610957957 Or Please send your full name, address and phone number along with the product code through message to place your order by phone / inbox Us. Product description: Leather Color : Black Buckles Color : Black Main Material: Buffalo Leather One part Leather Gender: Men 1 year Quality guarantee!!!Nice Look and Durable Belt, Great gift for men !! 100% Brand New & Top Quality Leather: Bangladeshi Buffalo Leather Measures: 120cm x 3.5cm Measures: 48",
// },
]

export default fakewishlist;